project:
  type: website
  output-dir: docs

website:
  title: "Olivia Hemond"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Portfolio


format:
  html:
    theme:
      - litera
      - styles.scss
    css: styles.css
    toc: true
    page-layout: full

editor: visual

